# Generated by Django 3.2.5 on 2021-07-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.author'),
        ),
    ]
