# Generated by Django 3.2.5 on 2021-07-28 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 7, 28, 14, 57, 56, 84951)),
        ),
    ]
