# Generated by Django 3.2.5 on 2021-07-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_comment_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='pub_date3',
        ),
    ]
