# Generated by Django 3.2.5 on 2021-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_pub_date_comment_pub_date3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date3',
            field=models.DateField(blank=True, default='12 june, 2021', null=True),
        ),
    ]
